version: "3.9"

services:
  app:
    image: node:18-alpine
    container_name: 'SchoolCall_app'
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: >
      sh -c "
        yarn &&
        yarn dev
      "

  studio:
    image: node:18-alpine
    container_name: 'SchoolCall_studio'
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '5555:5555'
    command: >
      sh -c "
        yarn &&
        npx prisma studio
      "

  db:
    image: postgres:14.2
    container_name: 'SchoolCall_db'
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  
  express:
    image: node:18-alpine
    container_name: 'SchoolCall_socket'
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    command: >
      sh -c "
        yarn global add nodemon &&
        yarn &&
        yarn socket
      "
  
  nginx:
    image: nginx:1.21-alpine
    container_name: 'SchoolCall_nginx'
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - express