version: "3.9"

services:
  app:
    image: node:18-alpine
    container_name: 'SchoolCall_app'
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
      - '5555:5555'
    command: >
      sh -c "
        yarn &&
        yarn dev
      "
      
  db:
    image: postgres:14.2
    container_name: 'SchoolCall_db'
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"