export const students = {
  address: 3601,
  seat: [
    { num: 2, name: '11 飯田 夢基', call_time: '2022-10-14T20:36:05.821Z'},
    { num: 3, name: '09', call_time: '' },
    { num: 4, name: '07', call_time: '' },
    { num: 5, name: '01', call_time: '' },
    { num: 8, name: '14', call_time: '' },
    { num: 9, name: '13', call_time: '' },
    { num: 10, name: '12', call_time: '' },
    { num: 11, name: '27', call_time: '' },
    { num: 12, name: '10', call_time: '' },
    { num: 13, name: '08', call_time: '' },
    { num: 14, name: '06', call_time: '' },
    { num: 15, name: '21', call_time: '2022-10-14T20:42:05.821Z' },
    { num: 16, name: '15', call_time: '' },
    { num: 17, name: '18 ', call_time: '' },
    { num: 18, name: '05', call_time: '' },
    { num: 20, name: '28', call_time: '' },
    { num: 21, name: '04', call_time: '' },
    { num: 22, name: '24', call_time: '' },
    { num: 23, name: '29', call_time: '' },
    { num: 24, name: '02', call_time: '' },
    { num: 25, name: '19', call_time: '' },
    { num: 26, name: '25', call_time: '' },
    { num: 27, name: '20', call_time: '' },
    { num: 28, name: '26', call_time: '' },
    { num: 29, name: '16', call_time: '' },
    { num: 30, name: '17', call_time: '' },
    { num: 32, name: '22', call_time: '' },
    { num: 33, name: '23', call_time: '' },
    { num: 34, name: '03', call_time: '' },
  ]
}

export const classroom = {
  address: 3601,
  seat: [
    [
      { num: 0, name: '' },
      { num: 1, name: '' },
      { num: 2, name: '' },
      { num: 3, name: '' },
      { num: 4, name: '' },
      { num: 5, name: '' },
      { num: 6, name: '' },
      { num: 0, name: '' }, 
    ],
    [
      { num: 0, name: '' },
      { num: 7, name: '' },
      { num: 8, name: '' },
      { num: 9, name: '' },
      { num: 10, name: '' },
      { num: 11, name: '' },
      { num: 12, name: '' },
      { num: 0, name: '教卓' }, 
    ],
    [
      { num: 0, name: '' },
      { num: 13, name: '' },
      { num: 14, name: '' },
      { num: 15, name: '' },
      { num: 16, name: '' },
      { num: 17, name: '' },
      { num: 18, name: '' },
      { num: 0, name: '' }, 
    ],
    [
      { num: 0, name: '' },
      { num: 19, name: '' },
      { num: 20, name: '' },
      { num: 21, name: '' },
      { num: 22, name: '' },
      { num: 23, name: '' },
      { num: 24, name: '' },
      { num: 0, name: '' }, 
    ],
    [
      { num: 0, name: '' },
      { num: 25, name: '' },
      { num: 26, name: '' },
      { num: 27, name: '' },
      { num: 28, name: '' },
      { num: 29, name: '' },
      { num: 30, name: '' },
      { num: 0, name: '柱' }, 
    ],
    [
      { num: 31, name: '' },
      { num: 32, name: '' },
      { num: 33, name: '' },
      { num: 34, name: '' },
      { num: 35, name: '' },
      { num: 36, name: '' },
      { num: 0, name: '' },
      { num: 0, name: '3Dプリンター' }, 
    ]
  ]
}