export const classroom = {
  desks: [
    [
      { seat_number: 0, name: '' },
      { seat_number: 1, name: '' },
      { seat_number: 2, name: '' },
      { seat_number: 3, name: '' },
      { seat_number: 4, name: '' },
      { seat_number: 5, name: '' },
      { seat_number: 6, name: '' },
      { seat_number: 0, name: '' }, 
    ],
    [
      { seat_number: 0, name: '' },
      { seat_number: 7, name: '' },
      { seat_number: 8, name: '' },
      { seat_number: 9, name: '' },
      { seat_number: 10, name: '' },
      { seat_number: 11, name: '' },
      { seat_number: 12, name: '' },
      { seat_number: 0, name: '教卓' }, 
    ],
    [
      { seat_number: 0, name: '' },
      { seat_number: 13, name: '' },
      { seat_number: 14, name: '' },
      { seat_number: 15, name: '' },
      { seat_number: 16, name: '' },
      { seat_number: 17, name: '' },
      { seat_number: 18, name: '' },
      { seat_number: 0, name: '' }, 
    ],
    [
      { seat_number: 0, name: '' },
      { seat_number: 19, name: '' },
      { seat_number: 20, name: '' },
      { seat_number: 21, name: '' },
      { seat_number: 22, name: '' },
      { seat_number: 23, name: '' },
      { seat_number: 24, name: '' },
      { seat_number: 0, name: '' }, 
    ],
    [
      { seat_number: 0, name: '' },
      { seat_number: 25, name: '' },
      { seat_number: 26, name: '' },
      { seat_number: 27, name: '' },
      { seat_number: 28, name: '' },
      { seat_number: 29, name: '' },
      { seat_number: 30, name: '' },
      { seat_number: 0, name: '柱' }, 
    ],
    [
      { seat_number: 31, name: '' },
      { seat_number: 32, name: '' },
      { seat_number: 33, name: '' },
      { seat_number: 34, name: '' },
      { seat_number: 35, name: '' },
      { seat_number: 36, name: '' },
      { seat_number: 0, name: '' },
      { seat_number: 0, name: '3Dプリンター' }, 
    ]
  ]
}

export const classwork = {
  classroom: classroom,
  class_name: "IE3A",
  students: [
    { seat_number: 2, name: '11', call_time: '2022-10-14T20:36:05.821Z'},
    { seat_number: 3, name: '09', call_time: '' },
    { seat_number: 4, name: '07', call_time: '' },
    { seat_number: 5, name: '01', call_time: '' },
    { seat_number: 8, name: '14', call_time: '' },
    { seat_number: 9, name: '13', call_time: '' },
    { seat_number: 10, name: '12', call_time: '' },
    { seat_number: 11, name: '27', call_time: '' },
    { seat_number: 12, name: '10', call_time: '' },
    { seat_number: 13, name: '08', call_time: '' },
    { seat_number: 14, name: '06', call_time: '' },
    { seat_number: 15, name: '21', call_time: '2022-10-14T20:42:05.821Z' },
    { seat_number: 16, name: '15', call_time: '' },
    { seat_number: 17, name: '18 ', call_time: '' },
    { seat_number: 18, name: '05', call_time: '' },
    { seat_number: 20, name: '28', call_time: '' },
    { seat_number: 21, name: '04', call_time: '' },
    { seat_number: 22, name: '24', call_time: '' },
    { seat_number: 23, name: '29', call_time: '' },
    { seat_number: 24, name: '02', call_time: '' },
    { seat_number: 25, name: '19', call_time: '' },
    { seat_number: 26, name: '25', call_time: '' },
    { seat_number: 27, name: '20', call_time: '' },
    { seat_number: 28, name: '26', call_time: '' },
    { seat_number: 29, name: '16', call_time: '' },
    { seat_number: 30, name: '17', call_time: '' },
    { seat_number: 32, name: '22', call_time: '' },
    { seat_number: 33, name: '23', call_time: '' },
    { seat_number: 34, name: '03', call_time: '' },
  ]
}
